#!/bin/bash

if [ "${side_current}" == "source" ] && [ -n "${snap_location_remote_source}" ]
	then	config_server_current=${snap_location_remote_source}
fi

if [ "${mode_create}" == "kvm" ]
	then	if [ -n "${config_server_current}" ]
			then	probe=$(ssh ${ssh_current} "qm list | grep ${sync_vmid_current}")
			else	probe=$(qm list | grep ${sync_vmid_current})
		fi

		if [ ! -n "${probe}" ]
			then	exit 80
		fi

	elif [ "${mode_create}" == "mysql" ] || [ "${mode_create}" == "pgsql" ]
		then	if [ "${mode_create}" == "mysql" ]
				then	if [ -n "${config_server_current}" ]
						then	probe=$(ssh ${ssh_current} "find ${config_options_sql} -maxdepth 0 2> /dev/null")
						else	probe=$(find ${config_options_sql} -maxdepth 0 2> /dev/null)
					fi

					if [ ! "${probe}" == "${config_options_sql}" ]
						then	exit 91
					fi

					if [ -n "${config_server_current}" ]
						then	probe=$(ssh ${ssh_current} "mysqlshow --defaults-extra-file=${config_options_sql}" | grep ${sync_name_source_current} | awk '{ print $2 }')
						else	probe=$(mysqlshow --defaults-extra-file=${config_options_sql} | grep ${sync_name_source_current} | awk '{ print $2 }')
					fi

					if [ ! "${probe}" == "${sync_name_source_current}" ]
						then	exit 93
					fi

				elif [ "${mode_create}" == "pgsql" ]
					then	if [ -n "${config_server_current}" ]
							then	probe=$(ssh ${ssh_current} "find /root/.pgpass -maxdepth 0 2> /dev/null")
							else	probe=$(find /root/.pgpass -maxdepth 0 2> /dev/null)
						fi

					if [ ! "${probe}" == "/root/.pgpass" ]
						then	exit 91
					fi

					if [ -n "${config_server_current}" ]
						then	probe=$(ssh ${ssh_current} "psql -l -U ${config_options_sql} -h localhost" | grep ${sync_name_source_current} | awk '{ print $1 }')
						else	probe=$(psql -l -U ${config_options_sql} -h localhost | grep ${sync_name_source_current} | awk '{ print $1 }')
					fi

					if [ ! "${probe}" == "${sync_name_source_current}" ]
						then	exit 93
					fi
			fi

			if [ -n "${config_certificate}" ]
				then	if [ -n "${config_server_current}" ]
						then	probe=$(ssh ${ssh_current} "find ${config_certificate} -maxdepth 0 2> /dev/null")
						else	probe=$(find ${config_certificate} -maxdepth 0 2> /dev/null)
					fi

					if [ ! -n "${probe}" ]
						then	exit 92
					fi
			fi


	else	:
fi

##### variable list. these will be picked up by debug #####
# import_fields = mode_create config_server_current ssh_current side_current snap_location_remote_source config_options_sql config_certificate sync_name_source_current sync_vmid_current
# export_fields =
