#!/bin/bash

if [ "${mode_snapshot}" == "file" ]
	then	if [ -n "{snap_new_source}" ]
			then	snap_rsync_source_current=${snap_new_source}
			else	exit 90
		fi
fi

if [ -n "${config_server_source}" ]
	then	command1="rsync ${config_options_rsync}${ssh_source_transfer}${snap_rsync_source_current}"
	else	command1="rsync ${config_options_rsync} ${snap_rsync_source_current}"
fi

if [ -n "${config_server_target}" ]
	then	command2="${ssh_target_transfer}${snap_rsync_target_current}"
	else	command2="${snap_rsync_target_current}/"
fi

if [ -n "${show_commands}" ]
	then	echo "${command1} ${command2}"
	else	eval ${command1} ${command2}
fi

##### variable list. these will be picked up by debug #####
# import_fields = mode_snapshot show_commands config_server_source ssh_source_transfer config_server_target ssh_target_transfer snap_new_source snap_rsync_source_current snap_rsync_target_current snap_new_source
# export_fields =
