#!/bin/bash

# if a dir name or synclistelement has spaces. so instead of for loop you have to use a while loop
sync_list_element=(${sync_list})
sync_list_element_number=$((${#sync_list_element[@]} -1))
bb="-1"

while [ "${sync_list_element_number}" -gt "${bb}" ]
do	# control variable
	bb=$((${bb} + 1))

	if [ ! "${mode_transfer}"  == "zfs" ]
		then	if [ -n "${elem_server_source}" ]
				then	probe_sync_name_elements=$(ssh ${ssh_source} "find \"${path_root_source}\"\"${path_offset_source}\"/${sync_list_element[bb]}* -maxdepth 0")
				else	probe_sync_name_elements=$(find "${path_root_source}""${path_offset_source}"/${sync_list_element[bb]}* -maxdepth 0)
			fi

			if [ "${mode_transfer}"  == "btrfs" ]
				then	for probe_sync_name_element in ${probe_sync_name_elements}
					do	if [ -n "${elem_server_source}" ]
							then	probe=$(ssh ${ssh_source} "btrfs subvolume show \"${probe_sync_name_element}\" 2> /dev/null" | head -1 | awk '{ print $1 }')
							else	probe=$(btrfs subvolume show "${probe_sync_name_element}" 2> /dev/null | head -1 | awk '{ print $1 }')
						fi

						if [ -n "${probe}" ]
							then	sync_name=${sync_name}'\n'${probe_sync_name_element}
						fi
					done

				else	sync_name=${sync_name}'\n'${probe_sync_name_elements}
			fi

		elif [ "${mode_transfer}"  == "zfs" ]
			then	if [ -n "${elem_server_source}" ]
					then	probe_sync_name_elements=$(ssh ${ssh_source} "zfs list -o name -r \"${path_snap_source}\"" | tail -n +3 | grep ${sync_list_element[bb]})
					else	probe_sync_name_elements=$(zfs list -o name -r "${path_snap_source}" | tail -n +3 | grep ${sync_list_element[bb]})
				fi
				sync_name=${syncname}'\n'${probe_sync_name_elements}

		else	:
	fi
done

sync_name=$(printf "${sync_name}" | grep -v '^$' | rev | cut -d "/" -f -1 | rev)
echo "${sync_name}"

##### variable list. these will be picked up by debug #####
# import_fields = mode_transfer elem_server_source ssh_source sync_list path_root_source path_snap_source
# export_fields = sync_name
