#!/bin/bash

# Read the config
# Logoptions
log_server=$(awk -v condition1="logserver" '$1 == condition1 { print $3 }' ${conf})
log_server_port=$(awk -v condition1="logserver" '$1 == condition1 { print $4 }' ${conf})
log_dir=$(awk -v condition1="logdirectory" '$1 == condition1 { print $3 }' ${conf})
log_usr=$(awk -v condition1="loguser" '$1 == condition1 { print $3 }' ${conf})

# Source-, Targetserver, Mode, Filesystem and general Options
config_server_source=$(awk -v condition1="sourceserver" '$1 == condition1 { print $3 }' ${conf})
config_port_source=$(awk -v condition1="sourceserver" '$1 == condition1 { print $4 }' ${conf})
config_server_target=$(awk -v condition1="targetserver" '$1 == condition1 { print $3 }' ${conf})
config_port_source=$(awk -v condition1="targetserver" '$1 == condition1 { print $4 }' ${conf})
config_mode=$(awk -v condition1="mode" '$1 == condition1 { print $3 }' ${conf})
config_fs=$(awk -v condition1="filesystem" '$1 == condition1 { print $3 }' ${conf})
config_options_rsync=$(awk -v condition1="rsync-options" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-)
config_options_mysql=$(awk -v condition1="mysql-options" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-)

# Source- and Targetdirectories/datastets and specific options for modes and filesystems
dir_snap_source=$(awk -v condition1="snapshot-directory" -v condition2="(source)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
if [ ! -n "${dir_snap_target_override}" ]
	then	dir_snap_target=$(awk -v condition1="snapshot-directory" -v condition2="(target)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
	else	dir_snap_target=${dir_snap_target_override}
fi
dir_root_source=$(awk -v condition1="root-directory" -v condition2="(source)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
dir_root_target=$(awk -v condition1="root-directory" -v condition2="(target)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
dir_offset_source=$(awk -v condition1="offset-directory" -v condition2="(source)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
dir_offset_target=$(awk -v condition1="offset-directory" -v condition2="(target)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})

# Snapshot Name, Dateformat, Name of the Snapshotlist and Number to keep. If one is 0, inkremential send/receive won´t work if snapshots are not handled by another script
if [ ! -n "${snap_name}" ]
	then	snap_name=$(awk -v condition1="snapshotformat" -v condition2="(name)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
fi
snap_date=$(awk -v condition1="snapshotformat" -v condition2="(date)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
snap_list_source=$(awk -v condition1="snapshotlist" -v condition2="(source)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
if [ ! -n "${snap_list_frequency_override}" ]
	then	snap_list_frequency_source=$(awk -v condition1="snapshotlist" -v condition2="(source)" '$1 == condition1 && $2 == condition2 { print $5 }' ${conf})
	else	snap_list_frequency_source=${snap_list_frequency_override}
fi
snap_list_location_source=$(awk -v condition1="snapshotlist" -v condition2="(source)" '$1 == condition1 && $2 == condition2 { print $6 }' ${conf})
snap_list_target=$(awk -v condition1="snapshotlist" -v condition2="(target)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
if [ ! -n "${snap_list_frequency_override}" ]
	then	snap_list_frequency_target=$(awk -v condition1="snapshotlist" -v condition2="(target)" '$1 == condition1 && $2 == condition2 { print $5 }' ${conf})
	else	snap_list_frequency_target=${snap_list_frequency_override}
fi
snap_list_location_target=$(awk -v condition1="snapshotlist" -v condition2="(target)" '$1 == condition1 && $2 == condition2 { print $6 }' ${conf})
if [ ! -n "${snap_limit_source}" ]
	then	snap_limit_source=$(awk -v condition1="snapshotnumber" -v condition2="(source)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
fi
if [ ! -n "${snap_limit_target}" ]
	then	snap_limit_target=$(awk -v condition1="snapshotnumber" -v condition2="(target)" '$1 == condition1 && $2 == condition2 { print $4 }' ${conf})
fi
# Syncdataoptions like Synclist, Names, Su- and Prefixes and VMID
sync_list=$(awk -v condition1="synclist" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-)
sync_name=($(awk -v condition1="syncname" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-))
sync_name_filetype=$(awk -v condition1="filetype" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-)
sync_name_new=($(awk -v condition1="newsyncname" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-))
sync_name_new_suffix=($(awk -v condition1="syncnamesuffix" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-))
sync_name_new_prefix=($(awk -v condition1="syncnameprefix" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-))
sync_vmid=($(awk -v condition1="VM-ID" '$1 == condition1 { print $0 }' ${conf} | cut -d " " -f 3-))

export log_server log_server_port log_dir log_usr
export config_server_source config_server_target config_options_rsync config_options_mysql
export dir_offset_source dir_offset_target
export snap_name snap_date snap_list_source snap_list_frequency_source snap_list_location_source snap_list_target snap_list_frequency_target snap_list_location_target
export sync_list sync_name_filetype sync_vmid

config_fields="log_server log_server_port log_dir log_usr config_server_source config_port_source config_server_target config_port_target config_mode config_fs config_options_rsync config_options_mysql dir_snap_source dir_snap_target dir_root_source dir_root_target dir_offset_source dir_offset_target snap_name snap_date snap_list_source snap_list_frequency_source snap_list_location_source snap_list_target snap_list_frequency_target snap_list_location_target snap_limit_source snap_limit_target sync_list sync_name sync_name_filetype sync_name_new sync_name_new_suffix sync_name_new_prefix sync_vmid"