#!/bin/bash

for sync_list_element in ${sync_list}
do	if [ ! "${mode_transfer}"  == "zfs" ]
		then	if [ -n "${config_server_source}" ]
				then	probe_sync_name_elements=$(ssh ${config_server_source}${config_port_source} "find ${dir_root_source}/${sync_list_element}* -maxdepth 0")
				else	probe_sync_name_elements=$(find ${dir_root_source}/${sync_list_element}* -maxdepth 0)
			fi

			if [ "${mode_transfer}"  == "btrfs" ]
				then	probe=$(echo ${probe_sync_name_elements} | grep '\\' 2> /dev/null)

					if [ -n "${probe}" ]
						then	exit 90
					fi

					for probe_sync_name_element in ${probe_sync_name_elements}
					do	if [ -n "${config_server_source}" ]
							then	probe=$(ssh ${config_server_source}${config_port_source} "btrfs subvolume show ${probe_sync_name_element} 2> /dev/null" | head -1 | awk '{ print $1 }')
							else	probe=$(btrfs subvolume show ${probe_sync_name_element} 2> /dev/null | head -1 | awk '{ print $1 }')
						fi

						if [ -n "${probe}" ]
							then	sync_name=${sync_name}'\n'${probe_sync_name_element}
						fi
					done

				else	sync_name=${sync_name}'\n'${probe_sync_name_elements}
			fi

		elif [ "${mode_transfer}"  == "zfs" ]
			then	if [ -n "${config_server_source}" ]
					then	probe_sync_name_elements=$(ssh ${config_server_source}${config_port_source} "zfs list -r ${dir_snap_source}" | awk '{ print $1 }' | tail -n +3 | grep ${sync_list_element})
					else	probe_sync_name_elements=$(zfs list -r ${dir_snap_source} | awk '{ print $1 }' | tail -n +3 | grep ${sync_list_element})
				fi
				sync_name=${syncname}'\n'${probe_sync_name_elements}

		else	:
	fi
done

sync_name=$(printf "${sync_name}" | grep -v '^$' | rev | cut -d "/" -f -1 | rev)
echo "${sync_name}"
